./print_puzzle.py ../test_month/May0214.puz >> clues.txt
./print_puzzle.py ../test_month/May0314.puz >> clues.txt
./print_puzzle.py ../test_month/May0414.puz >> clues.txt
./print_puzzle.py ../test_month/May0514.puz >> clues.txt
./print_puzzle.py ../test_month/May0614.puz >> clues.txt
./print_puzzle.py ../test_month/May0714.puz >> clues.txt
./print_puzzle.py ../test_month/May0814.puz >> clues.txt
./print_puzzle.py ../test_month/May0914.puz >> clues.txt
./print_puzzle.py ../test_month/May1114.puz >> clues.txt
./print_puzzle.py ../test_month/May1214.puz >> clues.txt
./print_puzzle.py ../test_month/May1314.puz >> clues.txt
./print_puzzle.py ../test_month/May1414.puz >> clues.txt
./print_puzzle.py ../test_month/May1514.puz >> clues.txt
./print_puzzle.py ../test_month/May1614.puz >> clues.txt
./print_puzzle.py ../test_month/May1714.puz >> clues.txt
./print_puzzle.py ../test_month/May1814.puz >> clues.txt
./print_puzzle.py ../test_month/May1914.puz >> clues.txt
./print_puzzle.py ../test_month/May2014.puz >> clues.txt
./print_puzzle.py ../test_month/May2114.puz >> clues.txt
./print_puzzle.py ../test_month/May2214.puz >> clues.txt
./print_puzzle.py ../test_month/May2314.puz >> clues.txt
./print_puzzle.py ../test_month/May2414.puz >> clues.txt
./print_puzzle.py ../test_month/May2514.puz >> clues.txt
./print_puzzle.py ../test_month/May2614.puz >> clues.txt
./print_puzzle.py ../test_month/May2714.puz >> clues.txt
./print_puzzle.py ../test_month/May2814.puz >> clues.txt
./print_puzzle.py ../test_month/May2914.puz >> clues.txt
./print_puzzle.py ../test_month/May3014.puz >> clues.txt
./print_puzzle.py ../test_month/May3114.puz >> clues.txt
